### ISSUE TITLE
hardcoded header url in login page

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra-gateway#117]
should use `headerScript` from `default.properties` in https://github.com/georchestra/georchestra-gateway/blob/main/gateway/src/main/resources/templates/login.html#L9 .. and maybe others ?

**Comment by pmauduit** [comment]
the logout page having been removed with c2485958231b08eb689f4eb23f78d37d4eadf770, not sure it is used in other places.

**Comment by pmauduit** [comment]
it does not look like, i'll PR with a bit of documentation around it.
