### ISSUE TITLE
Redirect behavior differences on ?login when header-authentication (sec-*) is enabled and is not enabled

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/georchestra-gateway#132]
On `?login`, for example for `/geonetwork/?login`, gateway does not redirect the same way between when header-authentication (sec-*) is enabled and is not enabled.

```
georchestra:
  gateway:
    security:
      header-authentication:
        enabled: true
```

It seems like when header-authentication (sec-*) is enabled, gateway will redirect to /login only if it finds `text/html` in the `Accept` header. If it doesn't, it will try to force basic auth to the client.

### With no Accept header

```
edevos@wrk67:~$ curl -I "https://geodata.dev.inrae.fr/geonetwork/?login"
HTTP/2 401 
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: 0
pragma: no-cache
referrer-policy: no-referrer
strict-transport-security: max-age=31536000 ; includeSubDomains
www-authenticate: Basic realm="Realm"
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
date: Mon, 24 Jun 2024 10:48:45 GMT
```

### With "text/html" in the Accept header

```
edevos@wrk67:~$ curl -I -H "accept: text/html" https://geodata.dev.inrae.fr/geonetwork/?login
HTTP/2 302 
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: 0
location: /login
pragma: no-cache
referrer-policy: no-referrer
strict-transport-security: max-age=31536000 ; includeSubDomains
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
date: Tue, 25 Jun 2024 15:48:22 GMT
```

### With no Accept header

```
edevos@wrk67:~$ curl -I "https://data.lillemetropole.fr/geonetwork/?login"
HTTP/2 302 
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: 0
location: /login
pragma: no-cache
referrer-policy: no-referrer
strict-transport-security: max-age=31536000 ; includeSubDomains
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
date: Tue, 25 Jun 2024 15:50:21 GMT
```

### With "text/html" in the Accept header

```
edevos@wrk67:~$ curl -I -H "accept: text/html" https://data.lillemetropole.fr/geonetwork/?login
HTTP/2 302 
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: 0
location: /login
pragma: no-cache
referrer-policy: no-referrer
strict-transport-security: max-age=31536000 ; includeSubDomains
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
date: Tue, 25 Jun 2024 15:50:46 GMT
```

----------

Due to this redirection behavior, this breaks geonetwork metadata visualization page. The user receives an authentication popup dialog and has to decline it in order to have the page fully loaded.

![image](https://github.com/georchestra/georchestra-gateway/assets/121870973/3134a424-688d-495c-a506-de6bfce8830c)

**Comment by groldan** [comment]
I couldn't find a relationship between the ` georchestra.gateway.security.header-authentication.enabled` configuration and the reported defect.
With `1.0.0`, the defect is visible regardless of the mentioned configuration setting.

I've created the following pull requests that as far as I can tell fixes it for good:
* https://github.com/georchestra/georchestra-gateway/pull/133
* https://github.com/georchestra/datadir/pull/415

Looking forward to your comments.
