### ISSUE TITLE
logout does not remove geoserver session, leaving next login with old credentials

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra-gateway#14]
To reproduce:

log in as testadmin/testadmin  against LDAP
access geoserver
logout
log in as testuser/testuser
access geoserver
Still got the admin rights.

The geoserver JSESSIONID is not cleared at logout.

Will be the same for any other stateful backend service

**Comment by groldan** [comment]
I'm ooo, but as a reminder, turns out it's not about gateway handling cookies in any way, but about geoserver's http headers authentication filter getting the authentication object from an internal cache instead of clearing out the security context once the gateway stops sending the sec-username header.
Solved in gscloud with its own "gateway" preauth filter

**Comment by fvanderbiest** [comment]
Witnessed the issue today during a training session.
Very scary stuff ... 

This can be investigated with GSMEL-261
