### ISSUE TITLE
CAS likely to be unsupported

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra-gateway#2]
From my understanding, this webapp is a reactive one, and actually runs on top of a network framework named netty (no jetty nor tomcat involved).

In order to continue to support CAS authentication with this project, we would either need:

* a reactive cas client (See https://github.com/spring-projects/spring-security/issues/5887)
* configure the CAS endpoint to act as a oauth2/openid-connect provider, as a reactive oauth2 client already exists (and is used in here).

**Comment by landryb** [comment]
from my understanding with CAS 6 it can 'easily' be configured as an oauth2 provider ? I have drupal and nextcloud talking to CAS, and if i can avoid trying to figure out how to connect those to oauth2 instead of CAS...

**Comment by pmauduit** [comment]
> from my understanding with CAS 6 it can 'easily' be configured as an oauth2 provider ?

Yes indeed, that was the purpose of the 2nd bullet point in my first comment. You can put the following file into your `/etc/georchestra/cas/services`:

```
$ cat oauth2-2001.json 
{
  "@class" : "org.apereo.cas.support.oauth.services.OAuthRegisteredService",
  "clientId": "external-oauth2",
  "clientSecret": "aaaa",
  "serviceId" : "^(https|http)://.*",
  "name" : "oauth2",
  "id" : 2001
}
```

Configure your application to consume this oauth2 endpoint:

```
client ID: external-oauth2 # clientId above
client secret: aaaa # clientSecret above
access token uri: https://url.to/cas/oauth2.0/accessToken
user authorization uri: https://url.to/cas/oauth2.0/authorize
user info uri: https://url.to/cas/oauth2.0/profile
```

and you should be good to go, the needed dependencies are already added to the georchestra cas overlay webapp, to support such configurations:
https://github.com/georchestra/georchestra-cas-server/blob/master/build.gradle#L77

**Comment by pmauduit** [comment]
Using CAS with the integrated oauth2 provider sounds like a reasonable workaround.
