### ISSUE TITLE
Add bot to update config submodule

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra-gateway#56]
Seems renovate is able to auto-merge PRs, contrary to dependabot.
Please investigate

**Comment by jeanmi151** [comment]
I added submodules dependabot, here https://github.com/georchestra/georchestra-gateway/commit/c5b62e4e140ae93fb8d0e8ceae050b0bad90dd75
Closing only if we see it working in the few days

**Comment by jeanmi151** [comment]
doesn't seams to work, I think we need to enable something in settings but I haven't the right acces, @pmauduit an idea ?

**Comment by groldan** [comment]
Closing as superseded by #71, we no longer use the georchestra datadir as a submodule.
