### ISSUE TITLE
Continuous build/integration workflows

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra-gateway#7]

**Comment by pmauduit** [comment]
A `DOCKER_HUB_USERNAME` & `DOCKER_HUB_PASSWORD` is available as secrets for the github actions.

About the repository name, I'd suggest to go for `georchestra/gateway`, and for the coherence, I think we will need some maven-fu to have a generic war / debian package also being generated.

**Comment by pmauduit** [comment]
i created an embryo here:
https://github.com/georchestra/georchestra-gateway/blob/main/.github/workflows/docker.yml

When pushing into `main`, a docker image is automatically pushed onto the `georchestra/gateway` repository on docker hub: https://hub.docker.com/repository/docker/georchestra/gateway/tags?page=1&ordering=last_updated

I also activated dependabot & added the suggested github action for CodeQL analysis (I haven't checked yet what it produced, but having static analysis sounded interesting to me).
